name: Process All Documents

on:
  push:
    paths:
      - 'documents/backend/*.md'
      - 'documents/frontend/*.md'
  pull_request:
    paths:
      - 'documents/backend/*.md'
      - 'documents/frontend/*.md'
  workflow_dispatch:

jobs:
  process-documents:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup permissions
        run: |
          chmod +x ./script/parsing-entb.sh
          chmod +x ./script/parsing-entf.sh
          chmod +x ./script/validate-entb.sh
          chmod +x ./script/validate-entf.sh

      - name: Identify changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files: |
            documents/backend/*.md
            documents/frontend/*.md

      - name: Process backend documents
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: |
          echo "Processing backend documents..."
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == documents/backend/*.md ]]; then
              echo "Validating backend file: $file"
              if ./script/validate-entb.sh "$file"; then
                echo "Parsing backend file: $file"
                ./script/parsing-entb.sh "$file"
              else
                echo "Validation failed for $file"
                exit 1
              fi
            fi
          done

      - name: Process frontend documents
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: |
          echo "Processing frontend documents..."
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == documents/frontend/*.md ]]; then
              echo "Validating frontend file: $file"
              if ./script/validate-entf.sh "$file"; then
                echo "Parsing frontend file: $file"
                ./script/parsing-entf.sh "$file"
              else
                echo "Validation failed for $file"
                exit 1
              fi
            fi
          done

      - name: Commit changes
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add documents/api/ documents/component/ documents/function/
          git diff --staged --quiet || git commit -m "자동 문서 생성: $(date +%Y-%m-%d)"
          git push